name: Publish to Digital Ocean Container Registry

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t integrations/integrator-ui .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_TOKEN}}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag image
        run: docker tag integrations/integrator-ui registry.digitalocean.com/integrator-container-registry/integrator-ui:${{github.event.inputs.version }}

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/integrator-container-registry/integrator-ui:${{ github.event.inputs.version }}
